Dev
offorma/Minteey pull request #1
Opened 2019-03-01 23:52 UTC by tafodinho

2019-03-02 01:11 UTC, zlayabekrija requested changes
Nice work, yet bootstrap isn't allowed for this project. I've seen that you have used a minimum of BS, but still I would like to ask you to remove any bootstrap from this project.
Kindly fix and resubmit review request.
Happy Coding

2019-03-02 01:11 UTC, zlayabekrija commented on assets/css/style.css
> +    margin: 5% 5px 5% 5px;
This could be written as margin: 5% 5px 
But please don't use % for padding or margin.

2019-03-02 18:36 UTC, oluwoleilesanmi requested changes
Good job @tafodinho @offorma  its good that, your commit messages start with verbs, good use of relative units of measure ems\% and a nice and clean html. **make changes to css below and you are good to go**. well done

This is not compulsory but here is a [Css Linter](http://csslint.net) it helps with keeping up with css best practices.

2019-03-02 18:36 UTC, oluwoleilesanmi commented on assets/css/style.css
> +.inline-list {
It is good practice to have a reset.css file.
- reset.css helps with avoiding repetition.
- reset.css helps with setting elements to default. 

The below should be moved to reset.css file.
```
margin: 0px;
padding: 0px;
```

2019-03-02 18:36 UTC, oluwoleilesanmi commented on assets/css/style.css
> +.form-top-text1 {
property should be moved to reset.css file.
```
margin: 0px; 
```

2019-03-02 18:36 UTC, oluwoleilesanmi commented on assets/css/style.css
> +.signup-text {
The two properties should be moved to reset.css file.
```
margin: 0px;
padding: 0px;
```

2019-03-02 18:36 UTC, oluwoleilesanmi commented on assets/css/style.css
> +.form-section {
Remove empty selector.

2019-03-04 19:32 UTC, oluwoleilesanmi approved these changes
@tafodinho @offorma :+1: job well done

2019-04-09 10:42 UTC, merged